apiVersion: v1
kind: Service
metadata:
  name: fee-insights
  labels:
    app: fee-insights
spec:
  type: ClusterIP
  selector:
    app: fee-insights
  ports:
    - name: http
      port: 8000
      targetPort: 8000
